name: fix-style

on:
  push:
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv

      - name: Install Dependencies
        run: mkdir -p tools/php-cs-fixer
            composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer 
            composer install --prefer-dist

      - name: Fix Style
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --diff

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling changes